# Site settings
title: Winodows App Studio Documentation
email: 
description: > # this means to ignore newlines until "baseurl:"
  Winodows App Studio Github Documentation
baseurl: "" 
url: "http://wasteam.github.io/"
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]